### ISSUE TITLE
Polish Translation Precentege

### ISSUE THREAD

**Issue by ByteBolt556** [Dysnomia-Studio/factory-game-i18n#3]
Hello. I've noticed that in the readme file Polish translation is still at 99% and I'm pretty sure I have translated all the files. Can you please check and let me know if I missed something? Thanks in advance!

**Comment by Elanis** [comment]
Hi :)
It's because I added both the `"reset-tutorial"` and `"reset-tutorial-done"` strings inside the "settings" file.

There will be other strings added through the development.

**Comment by ByteBolt556** [comment]
Oh I didn't notice those! Sorry. I'll be keeping a watch on those in the future 😊

**Comment by Elanis** [comment]
No worries :) And thanks for your help!
